version: '3'

services:
  web:
    build:
        context: .
        dockerfile : Dockerfile
    ports:
     - "6153:80"
    depends_on:
     - redis
     
  redis:
    image: "redis"
    ports: 
     - "6379:6379"